[tool.poetry]
name = "streamsight"
version = "0.2.9a2"
description = "A toolkit for offline evaluation of Recommender Systems"
authors = ["Ng Tze Kean <ngtzekean@gmail.com>"]
readme = "README.md"
repository = "https://github.com/HiIAmTzeKean/Streamsight"
documentation = "https://hiiamtzekean.github.io/Streamsight/"
keywords = ["RecSys", "toolkit", "streamsight"]

[tool.poetry.dependencies]
python = "^3.12"
colorama = "^0.4.6"
colorlog = "^6.8.2"
pyyaml = "^6.0.1"
scikit-learn = "^1.4.1.post1"
pandas = "^2.2.2"
numpy = "^1.26.4"
urllib3 = "^2.2.1"
tqdm = "^4.66.4"
progressbar = "^2.5"
typing-extensions = "^4.12.2"
deprecation = "^2.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
ipykernel = "^6.29.3"
black = "^24.4.2"
simplejson = "^3.19.3"
sphinxcontrib-bibtex = "^2.6.2"
setuptools = "^73.0.0"
sphinx = "7.4.7"
sphinx-rtd-theme = "^2.0.0"
ipywidgets = "^8.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
